##############################################################################################################################
file = open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt")
buffer = file.read()
print("------------[file -> buffer || print(buffer)]------------\n")
print(buffer)
file.close()
##############################################################################################################################
file = open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt")
print("\n------------[reading line by line]------------")
print(file.readline().strip())
print(file.readline().strip())
print(file.readline().strip())
print(file.readline().strip())
print(file.readline().strip())
print(file.readline().strip())
file.close()
##############################################################################################################################
print()
print("------------[with open ("") as file:]------------")
with open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt") as file:   # automatically perform file.close()
    print(file.readline().strip())
    print(file.readline().strip())
    print(file.readline().strip())
    print(file.readline().strip())
    print(file.readline().strip())

with open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt") as file:   # automatically perform file.close()
    print()
    print(file.read())
##############################################################################################################################
print()
print("------------[with open ("") as file: UPPERCASE]------------")
with open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt") as file:   # automatically perform file.close()
    print(file.readline().strip().upper())
    print(file.readline().strip().upper())
    print(file.readline().strip().upper())
    print(file.readline().strip().upper())
    print(file.readline().strip().upper())

with open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt") as file:   # automatically perform file.close()
    print()
    print(file.read().upper())
##############################################################################################################################
print()
print("------------[file.readlines() -> line_buffer || print(buffer)]------------\n")
file = open("python/04.IT_automation_with_python/02.os_operation_system/2_0.spider.txt")
lines = file.readlines()
file.close()
lines.sort()
print(lines)